# Problem 2
# 
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed
# four million.

require 'rubygems'
require 'pp'

UPPER_BOUND     = 4000000

fibonacci_values = Array.new
fibonacci_values[0] = 1

sum_of_evens    = 0

while fibonacci_values.last < UPPER_BOUND
  if fibonacci_values.last%2 == 0
    sum_of_evens += fibonacci_values.last
  end
  fibonacci_values << fibonacci_values.last + fibonacci_values[fibonacci_values.length-2]
  pp fibonacci_values.last
end

pp "Sum of all even numbers in the Fibonnaci sequence up to #{UPPER_BOUND}: #{sum_of_evens}"